import Image from "next/image";
import "./globals.css";
import Nav from "./components/Nav";
import Button from "./components/Button";
import { CiSearch } from "react-icons/ci";
import { VscAccount } from "react-icons/vsc";
import { CiShoppingCart } from "react-icons/ci";
import Link from "next/link";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/*  Header  */}
        <header className="w-full flex justify-around items-center">
          <Image src="/logo.webp" alt="logo" width={150} height={150} />

          <Nav />
          <div className="flex justify-center items-center gap-1">
            <Button className="text-3xl" text={<CiSearch />} />
            <Link href="/login">
              <Button
                className="text-3xl font-light cursor-pointer hover:scale-95 transition-all duration-200"
                text={<VscAccount />}
              />
            </Link>
            <div className="flex justify-center items-center">
              <Button className="text-3xl " text={<CiShoppingCart />} />
              <Button
                className="bg-black text-white text-sm w-5 rounded-full"
                text="1"
              />
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
