import "./globals.css";
import Header from "./components/Header";

export const metadata = {
  title: "Chic Closet",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.webp",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/*  Header  */}
        <Header />

        {children}
      </body>
    </html>
  );
}
